return {
  instruments = {
    BITU  = { increment = 10, maxShares = 100, group = "BITCOIN" },
    DUST  = { increment = 10, maxShares = 100, group = "MINERS" },
    GDX   = { increment = 10, maxShares = 100, group = "MINERS" },
    GLD   = { increment = 10, maxShares = 100, group = "GOLD" },
    NUGT  = { increment = 10, maxShares = 100, group = "MINERS" },
    SBIT  = { increment = 10, maxShares = 100, group = "BITCOIN" },
    SCO   = { increment = 10, maxShares = 100, group = "OIL" },
    SPXL  = { increment = 10, maxShares = 100, group = "SP500" },
    SPXS  = { increment = 10, maxShares = 100, group = "SP500" },
    UCO   = { increment = 10, maxShares = 100, group = "OIL" },
    EASY  = { increment = 10, maxShares = 100, group = "TEST" },
    RANDOM = { increment = 10, maxShares = 100 },
  },
  groups = {
    BITCOIN = { range = { 3500, 110000 } },
    OIL     = { range = { 10, 100 } },
    MINERS  = { range = { 23, 67 } },
    GOLD    = { range = { 2000, 5000 } },
    SP500   = { range = { 4000, 7300 } },
    TEST    = { range = { 85, 175 } },
  },
  features = {
    buyButton      = 0,
    sellButton     = 0,
    buyStopButton  = 200,
    sellStopButton = 250,
    stopLossButton = 100,
    flatButton     = 0,
    cancelButton   = 150,
    signalButtons  = 0,
    slowMA         = 350,
    mediumMA       = 400,
    priceLine      = 0,
    gridLines      = 50,
    orderLines     = 0,
    cross          = 1000,
    algo2          = 2000,
    algo3          = 3000,
    algo4          = 4000,
    algo5          = 5000,
    algo6          = 6000,
    algo7          = 7000,
    algo8          = 8000,
    algo9          = 9000,
    snow           = false,
    ball           = true,
    skier          = false,
    surfer         = false,

    -- Canvas sprites (unlocked by events, not PnL)
    sprite_paws    = false,
    sprite_bear    = false,
    sprite_blob_fish = false,
    sprite_blond_suit = false,
    sprite_bucket  = false,
    sprite_bull    = false,
    sprite_come_back = false,
    sprite_come_back_no = false,
    sprite_diamond = false,
    sprite_diamond_hands = false,
    sprite_dive_dip = false,
    sprite_hide_cats_eyes = false,
    sprite_horse_squinting = false,
    sprite_leonardette = false,
    sprite_liquidate = false,
    sprite_milkshake = false,
    sprite_money_house = false,
    sprite_paper_hands = false,
    sprite_pink_scream_guy = false,
    sprite_play_ball = false,
    sprite_play_dog = false,
    sprite_play_paws = false,
    sprite_portfolio = false,
    sprite_replicator = false,
    sprite_rocket = false,
    sprite_smiling_visor_cat = false,
    sprite_tendy = false,
    sprite_water_bear = false,
    sprite_wtf_girl = false,
  },
  algos = {
    { key = "cross",  label = "CROSS\nTAKE",  color = {0.48, 0.41, 0.93} },
    { key = "algo2",  label = "SL\nFOLLOW", color = {0.91, 0.25, 0.38} },
    { key = "algo3",  label = "ALGO\n3", color = {0.20, 0.80, 0.60} },
    { key = "algo4",  label = "ALGO\n4", color = {0.94, 0.71, 0.16} },
    { key = "algo5",  label = "ALGO\n5", color = {0.35, 0.42, 0.48} },
    { key = "algo6",  label = "ALGO\n6", color = {0.70, 0.30, 0.85} },
    { key = "algo7",  label = "ALGO\n7", color = {0.05, 0.40, 0.15} },
    { key = "algo8",  label = "ALGO\n8", color = {0.72, 0.19, 0.30} },
    { key = "algo9",  label = "ALGO\n9", color = {0.25, 0.50, 0.80} },
  },
  canvasSprites = {
    { file = "bear.png" },
    { file = "blob_fish.png" },
    { file = "blond_suit.png" },
    { file = "bucket.png" },
    { file = "bull.png" },
    { file = "come_back.png" },
    { file = "come_back_no.png" },
    { file = "diamond.png" },
    { file = "diamond_hands.png" },
    { file = "dive_dip.png" },
    { file = "hide_cats_eyes.png" },
    { file = "horse_squinting.png" },
    { file = "leonardette.png" },
    { file = "liquidate.png" },
    { file = "milkshake.png" },
    { file = "money_house.png" },
    { file = "paper_hands.png"},
    { file = "pink_scream_guy.png" },
    { file = "play_ball.png", size = 0.1 },
    { file = "play_dog.png", size = 0.1 },
    { file = "play_paws.png", size = 0.1 },
    { file = "portfolio.png" },
    { file = "replicator.png" },
    { file = "rocket.png" },
    { file = "smiling_visor_cat.png" },
    { file = "tendy.png", size = 0.1 },
    { file = "water_bear.png" },
    { file = "wtf_girl.png" },
  },
  canvasSpriteSizePct = 0.2,
  xerMA = { type = "TEMA", period = 15 },
  xeeMA = { type = "EMA", period = 15 },
  defaultLeverage = 1,
  defaultIterations = 5,
  stopStepPct = 0.001,
  music = {
    track = "music/EDM.mp3",
    bpm = 125,
  },
  tendyMenuChoices = {
    { id = "rewind",  label = "REWIND" },
    { id = "bucket",  label = "BUCKET" },
    { id = "redeem",  label = "REDEEM" },
  },
  debug = { 
    unlockAll = true,
  },
}
