return {
  instruments = {
    BITU  = { increment = 10, maxShares = 100, group = "BITCOIN" },
    DUST  = { increment = 10, maxShares = 100, group = "MINERS" },
    GDX   = { increment = 10, maxShares = 100, group = "MINERS" },
    GLD   = { increment = 10, maxShares = 100, group = "GOLD" },
    NUGT  = { increment = 10, maxShares = 100, group = "MINERS" },
    SBIT  = { increment = 10, maxShares = 100, group = "BITCOIN" },
    SCO   = { increment = 10, maxShares = 100, group = "OIL" },
    SPXL  = { increment = 10, maxShares = 100, group = "SP500" },
    SPXS  = { increment = 10, maxShares = 100, group = "SP500" },
    UCO   = { increment = 10, maxShares = 100, group = "OIL" },
    EASY  = { increment = 10, maxShares = 100, group = "EASY" },
    RANDOM = { increment = 10, maxShares = 100 },
  },
  groups = {
    BITCOIN = { range = { 3500, 110000 } },
    OIL     = { range = { 10, 100 } },
    MINERS  = { range = { 23, 67 } },
    GOLD    = { range = { 2000, 5000 } },
    SP500   = { range = { 4000, 7300 } },
    EASY    = { range = { 85, 175 } },
  },
  presidents = {
    { name = "Elon Musk",    image = "characters/presidents/elon_musk.png" },
    { name = "Donald Trump",  image = "characters/presidents/donald_trump.png" },
    { name = "Joe Rogan",     image = "characters/presidents/joe_rogan.png" },
    { name = "Taylor Swift",  image = "characters/presidents/taylor_swift.png" },
    { name = "Barack Obama",  image = "characters/presidents/barack_obama.png" },
    { name = "Mr. Beast",     image = "characters/presidents/mr_beast.png" },
  },
  events = {
    "Fed raises interest rates sharply",
    "Crypto ban proposed by regulators",
    "Oil supply shock hits markets",
    "Gold surges past all-time highs",
    "Tech earnings smash Wall Street estimates",
    "Trade war fears rattle investors",
    "Jobs report crushes economist forecasts",
    "AI chip shortage sparks panic",
    "Housing market crash worries grow",
    "Inflation data cooler than expected",
  },
  milestones = {
    { image = "memes/are_ya_winning_son.png", label = "Are ya winning, son?", copyrighted = false },
    { image = "memes/don_tzu_trader_stop_loss.png", label = "Don Tzu Stop Loss", copyrighted = true },
    { image = "memes/money_come_back_no.png", label = "Money Come Back", copyrighted = false },
    { image = "memes/big_short_bubble.png", label = "Big Short Bubble", copyrighted = true },
    { image = "memes/diamond_hands_grocery.png", label = "Diamond Hands Grocery", copyrighted = false },
    { image = "memes/jack_black_milkshake.png", label = "Jack Black Milkshake", copyrighted = true },
    { image = "memes/crying_mask_over.png", label = "Crying Mask Over", copyrighted = false },
    { image = "memes/gumby_cover_cat_eyes.png", label = "Gumby Cat Eyes", copyrighted = false },
    { image = "memes/honey_saved_house.png", label = "Honey Saved House", copyrighted = false },
  },
  features = {
    buyButton      = 0,
    sellButton     = 0,
    buyStopButton  = 200,
    sellStopButton = 250,
    stopLossButton = 100,
    flatButton     = 0,
    cancelButton   = 150,
    endDayButton   = 300,
    signalButtons  = 0,
    slowMA         = 350,
    mediumMA       = 400,
    priceLine      = 0,
    gridLines      = 50,
    orderLines     = 0,
  },
  stopStepPct = 0.001,
  debug = {
    unlockAll = false,
  },
}
